version: '3'

services:
  app:
    # Uncomment the next line to use a non-root user for all processes. You can also
    # simply use the "remoteUser" property in devcontainer.json if you just want
    # VS Code and its sub-processes (terminals, tasks, debugging) to execute as the user
    # On Linux, you may need to update the USER_UID and USER_GID in .devcontainer/Dockerfile 
    # to match your user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode

    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspace:cached
    ports:
      # - 8888:8888
      - 4000:4000
      - 3010:3010
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    # links: 
    #   - db
    
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: sqlpad
      POSTGRES_PASSWORD: sqlpad
  
  
  sqlpad:
    image: sqlpad/sqlpad:latest
    hostname: sqlpad
    ports:
      - 3000:3000
    environment:
      - SQLPAD_DEBUG=TRUE
    volumes:
      # This maps /var/lib/sqlpad directory inside sqlpad container to a directory docker host (your laptop, desktop, etc)
      # This allows your SQLPad data to exist across container shutdowns
      # For this to work, the path here `~/docker-volumes` must be shared with docker
      - ~/docker-volumes/sqlpad-postgres:/var/lib/sqlpad
    
  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   ports: 
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: LocalPassword
